# Generated by Django 5.0 on 2026-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='marked_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
