# Generated by Django 5.0 on 2026-02-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_marked_offensive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='marked_offensive',
            new_name='mark_inappropriate',
        ),
    ]
